version: 2

models:
  - name: mart_volatility_analysis
    description: "Final table for volatility analysis."
    columns:
      # Test the NEW explicit ID column
      - name: vol_id
        description: "Primary key (Ticker + Date)."
        tests:
          - unique
          - not_null

      - name: stock_date
        tests:
          - not_null
      
      - name: ticker
        tests:
          - not_null

      - name: is_high_volatility
        tests:
          - accepted_values:
              arguments:
                values: [true, false]